### ISSUE TITLE
Abfrage der Datenbank per Grafana

### ISSUE THREAD

**Issue by MoosHam** [x-jokay/docker-ccu-historian#13]
Moin, 
Danke für das Klasse Docker-Teil! Läuft auch auf Anhieb, allerdings habe ich es nicht hinbekommen, auf die Datenbank auf Port 5435 zuzugreifen. Kenne mich mit Docker noch nicht so gut aus, aber es sieht so aus, dass dieser Port auch gar nicht EXPOSED ist. 

Wäre das möglich, das zu ergänzen? Habe nämlich schon Grafana in einem anderen Container laufen und möchte die Daten von CCU Historian gerne anzuapfen :-)

Vielen Dank,
MoosHam

**Comment by x-jokay** [comment]
Hellu

Danke fürs Feedback 👍🏼 

Die Ports `8082`, `9092` und `5435` sind nun auch exposed.

Ist ab sofort im neusten container image enthalten und kann mittels `docker pull xjokay/ccu-historian:latest` geholt werden.

**Comment by MoosHam** [comment]
Super, vielen Dank für die schnelle Umsetzung! Port 8082 funktioniert auch, leider kann ich trotzdem in Grafana nicht auf den Postgresql zugreifen:
ständig: read tcp 172.x.x.x:49664->192.168.x.x:5435: read: connection reset by peer

habe schon alle möglichen Varianten für Database durch, eigentlich sollte es ja diese sein: "/database/history"

eine Idee?

**Comment by x-jokay** [comment]
Ich hab das selber so nicht konfiguriert, aber der config param `database.pgEnable` und `database.pgAllowOthers` sind korrekt gesetzt, siehe auch [Liste aller Optionen](https://github.com/mdzio/ccu-historian/wiki#liste-aller-optionen).

**Comment by x-jokay** [comment]
Habs mal kurz bei mir getestet.

Wenn ich folgende Werte verwende, funktioniert der Login via UI (:8082):

![sample-db](https://user-images.githubusercontent.com/18613935/94681075-18381780-0323-11eb-8f4e-58953f8092df.png)

Default-Passwort: `ccu-historian`.

Der Prefix der Url entspricht dem Wert vom config param `database.dir='/database'`.

**Comment by x-jokay** [comment]
Und beim Versuch via ODBC auf Port `:5435` erhalte ich diese Meldung:

![odbc-error](https://user-images.githubusercontent.com/18613935/94683006-1f145980-0326-11eb-8a9a-450338c7e9db.png)

**Comment by MoosHam** [comment]
PERFEKT! Danke, das wars!
database.pgEnable und database.pgAllowOthers in der Config von Hand auf true gesetzt, neu gestartet und funzt.

Kaum machts man richtig, klappts auch schon :-)

Der Login über port 8082 hat übrigens auch ohne die beiden Parameter schon funktioniert. Nur extern halt nicht...

Nochmal vielen Dank für den Docker und die rasche Hilfe!

**Comment by x-jokay** [comment]
Mittels [Azure Data Studio](https://chocolatey.org/packages/azure-data-studio) und der [PostgreSQL Extension](https://github.com/Microsoft/azuredatastudio-postgresql) kann ich eine Verbindung aufbauen:

![ads-1](https://user-images.githubusercontent.com/18613935/94684462-656ab800-0328-11eb-96c5-984a161000a7.png)

![ads-2](https://user-images.githubusercontent.com/18613935/94684479-68fe3f00-0328-11eb-9a1f-075a8e4a2857.png)

Erhalte dann aber diese Fehlermeldung:

```sh
[Error - 14:19:17] Request admin/getdatabaseinfo failed.
  Message: Unhandled exception while handling request method admin/getdatabaseinfo: "Function "PG_GET_USERBYID" not found; SQL statement:
SELECT pg_catalog.pg_get_userbyid(db.datdba) FROM pg_catalog.pg_database db WHERE db.datname = E'/database/history' [90022-199]
DETAIL:  org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "PG_GET_USERBYID" not found; SQL statement:
SELECT pg_catalog.pg_get_userbyid(db.datdba) FROM pg_catalog.pg_database db WHERE db.datname = E'/database/history' [90022-199]
"
  Code: -32603 
[Error - 14:19:17] Request metadata/list failed.
  Message: Unhandled exception while listing metadata
  Code: 0 
```

**Comment by MoosHam** [comment]
![image](https://user-images.githubusercontent.com/3285881/94684866-f17cdf80-0328-11eb-9e20-02528f91bd11.png)

also in Grafana klappt das wunderbar:
![image](https://user-images.githubusercontent.com/3285881/94685020-1f622400-0329-11eb-8066-b1c39c9c8a70.png)

Noch nicht genug Daten... Keine Ahnung was die Fehlermeldungen sagen sollen. So wie ich das verstanden habe, liegt hinter CCU-Historian eine H2 Datenbank, die nach aussen postgresql spricht. Aber in details steck ich nicht drin.

**Comment by bs0001** [comment]
Ich habe  nach wie vor das Problem, dass ich bei der Einrichtung der datasource in Grafana die Fehlermeldung erhalte:
db query error: failed to connect to server - please inspect Grafana server log for details

Die config-Parameter in der ccu-historian.config sind korrekt gesetzt (database.pgEnable und database.pgAllowOthers sowie database.dir='/database').
Per Konsole kann ich mich auf die Datenbank connecten und auch SQLs ausführen.

Die Ports im Docker der ccu-historian sind auch korrekt eingestellt. Per ccu-historian Oberfläche kann ich über die URL mit dem Port 8085 auch Charts erstellen lassen.
![image](https://user-images.githubusercontent.com/46260437/219496289-9b23e900-9fa2-4243-89c8-4ee536844f76.png)

Woran kann es noch liegen?

VG
Bernd


Was kann ich noch prüfen, um das Problem zu beheben?

**Comment by bs0001** [comment]
Ich konnte das Problem nun wie folg lösen.
Problem war, dass ich meine CCU-H-Daten nicht unter volume2/docker liegen habe, sondern auf einem anderen freigegeben Ordner im volume2.
Das hatte zur Folge, dass ich in die Config-Datei reinschreiben konnte, was ich wollte, er hat sie schlichtweg nicht gelesen.
Nun habe ich ausschließlich die Config-Datei unter volume2/docker/config abgelegt und diesen Pfad in der Anlage des Dockercontainers angegeben, was dann als Effekt hatte, dass ich all meine Einstellungen im Protokoll des Dockercontainers sehen konnte, dass diese gelesen und verarbeitet werden.

Hier ein Ausschnitt meines Einrichtungsskriptes für den Dockercontainer:
docker run -d --restart always --name=ccu-historian \
-v /volume2/SmXXX/PRD/CCU-H/ccu-historian/data:/database \
-v /volume2/SmXXX/PRD/CCU-H/ccu-historian/:/opt/ccu-historian \
-v /volume2/SmXXX/PRD/CCU-H/ccu-historian/config:/opt/ccu-historian/config \

Das hilft hoffentlich denjenigen weiter, die ein ähnliches Problem haben.

**Comment by jokay** [comment]
@bs0001 danke für die Info. Normalerweise wird doch in den Logs beim Start angezeigt, welche config geladen wird?

**Comment by bs0001** [comment]
ja, schon klar. Wenn es beim ersten Mal gleich korrekt funktioniert, dann sieht man das und versteht es auch.
Durch das, dass ich dabei bin, meine CCU-H vom Raspi auf die Synology zu verlagern im Docker Container, war es mein erster Versuch. Durch das, dass ich die ganzen Parameter bei der Erstellung des Docker-Containers mitgegeben habe, wurde auch die CCU-H-DB erreichbar, Von daher dachte ich, die Config wird gezogen. Nach ein paar Tests war es es klar, dass dem nicht so war. 
Das war dann auch der ausschlaggebende Punkt, wo ich das Problem suchen konnte.
Von daher bin ich nun froh, dass der Zugriff mit Grafana nun auch funktioniert, so dass ich mich nun um die Inhalte kümmern kann.
Danke im Übrigen für Dein Projekt hier!!

**Comment by bs0001** [comment]
Hallo zusammen,

nachdem ja die Verbindung zur ccu-historian DB aus Grafana erfolgreich war bin ich nun an dem Punkt, dass ich keine Tabellen angezeigt bekomme. SQL-Statements werden dagegen problemlos ausgeührt.
Hab auch schon diverse Sachen aus im Netz gesucht aber so wirklich sicher bin ich mir nicht, was ich ausführen soll, damit mir in der Dropdownbox die verfügbaren Tabellen angezeigt werden. Ich hoffe, jemand hat einen Tipp.
![image](https://user-images.githubusercontent.com/46260437/219955363-7c528eef-6758-4d74-a202-b94ec7f97a7d.png)

VG
Bernd

**Comment by jokay** [comment]
Ich nehme an das [hier](https://www.cyberdoc-net.de/2020/10/ccu-historian-daten-mit-grafana-visualisieren/) hast du bereits im Detail angeschaut?

**Comment by bs0001** [comment]
na klar. Aber genau bei dem Punkt wird nicht drauf eingegangen.
