### ISSUE TITLE
CONFIG_KEEP_MONTHS should be better documented

### ISSUE THREAD

**Issue by mdzio** [x-jokay/docker-ccu-historian#14]
The documentation should be extended:
By setting the environment variable CONFIG_KEEP_MONTHS, maintenance is performed before the CCU-Historian is actually started. One after the other the CCU-Historian is called with the options ` -clean`, `-recalc` and `-compact`.

See also: [Comment on CCU-Historian Issue](https://github.com/mdzio/ccu-historian/issues/113#issuecomment-737483900)

**Comment by x-jokay** [comment]
Good point, [information added](https://github.com/x-jokay/docker-ccu-historian/commit/c49c7a3a3c5dd2ddb5d39f9f70c00e282105d5f7).
