### ISSUE TITLE
Container Stops right after start

### ISSUE THREAD

**Issue by HPSwiss** [x-jokay/docker-ccu-historian#17]
Hi, 

running this container on docker, it stops after a few seconds with the following error in the log: 
standard_init_linux.go:219: exec user process caused: exec format error

Running it with the unchanged run parameters, except for the IPs.
Any idea what this could be?

Thanks and regards!
Hilmar

**Comment by x-jokay** [comment]
Hellu

I have no such error when running this command, it just works.

Do you try to run this container on a RaspberryPi as this won't work, it's currently not a multi-arch build.

**Comment by HPSwiss** [comment]
Hoi,

thanks for that hint, I was trying to run it on a RPi Cluster indeed! I‘m discovering docker... I‘ll make it MultiArch to try that. Thanks & regards from Zürich!

Hilmar

Sent from my iPhone

On 27. Dec 2020, at 07:53, D. Domig <notifications@github.com> wrote:

﻿
Hellu

I have no such error when running this command, it just works.

Do you try to run this container on a RaspberryPi as this won't work, it's currently not a multi-arch build.

**Comment by x-jokay** [comment]
@DannySotzny was starting a RPi build as well, no idea what the current status is.

- [GitHub - DannySotzny/docker-ccu-historian](https://github.com/DannySotzny/docker-ccu-historian)
- [DockerHub - dsotzny/ccu-historian](https://hub.docker.com/r/dsotzny/ccu-historian)

Currently I have no time to create a multi-arch or RPi build but [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx) looks promising.

I will close this issue as RPi is currently unsupported.

**Comment by HPSwiss** [comment]
Hi again,

I managed to get a build running on ARM32v7 for the RPI by forking your files as below.
Great learning curve

The docker-entrypoint.sh executes well and starts the CCU-Historian as per the log.

I have two issues however:
- no monotonic clock available & date and time stays in the 1970-ies
- Historian does not respond to the 80 or 8082 port, though exposed (and the health check on local port times out as well)

Do you have any idea what the issue could be and where I could dig?

Thanks a lot and Gruss,

Hilmar





Dockerfile:
ARG VERSION=2.5.2
ARG CHECKSUM=2bf0347c8f1f2270c6095f18ce29c6f6c5bf7da90ce080bc2eab1e497cb5723672c51b0dbcfca1300026f9647050a3c1ca4b26f116e21ff54b686337b7607b99
FROM arm32v7/debian:buster AS builder
ARG VERSION
ARG CHECKSUM
ENV VERSION ${VERSION}
RUN  apt-get update -y && apt-get install unzip
WORKDIR /tmp
RUN mkdir /tmp/ccu-historian
WORKDIR /tmp/ccu-historian
ADD https://github.com/mdzio/ccu-historian/releases/download/${VERSION}/ccu-historian-${VERSION}-bin.zip <https://github.com/mdzio/ccu-historian/releases/download/$%7BVERSION%7D/ccu-historian-$%7BVERSION%7D-bin.zip> .
RUN unzip ccu-historian-${VERSION}-bin.zip && \
    rm ccu-historian-${VERSION}-bin.zip
WORKDIR /tmp

#RUN echo "${CHECKSUM}  ccu-historian-${VERSION}-bin.zip" | sha512sum -c - && \
#    mkdir /tmp/ccu-historian && \
#    unzip ccu-historian-${VERSION}-bin.zip -d /tmp/ccu-historian

FROM adoptopenjdk:latest
ARG VERSION
ENV VERSION ${VERSION}
ENV TZ UTC
WORKDIR /opt/ccu-historian
RUN mkdir -p /database && \
    echo ${TZ} > /etc/timezone
COPY --from=builder /tmp/ccu-historian /opt/ccu-historian
VOLUME ["/opt/ccu-historian/config", "/database"]
COPY ./docker-entrypoint.sh /

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh”]

EXPOSE 80 2098 2099 8082 9092 5435               
#HEALTHCHECK --interval=1m --timeout=3s \
#    CMD curl -f http://localhost/historian <http://localhost/historian> || exit 1

**Comment by x-jokay** [comment]
@HPSwiss I'm not sure why it's not working for you but I have now setup the multi-platform build using [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/).

Would it be possible for you to run a test on your RaspberryPi using the following:

```sh
docker pull xjokay/ccu-historian:dev
```

If it works for you, I can add it and provide images for all this platforms:

- linux/amd64
- linux/arm/v7
- linux/arm64/v8
- linux/ppc64le
- linux/s390x

**Comment by x-jokay** [comment]
@DannySotzny may be you could give this a try as well?
