### ISSUE TITLE
V2.3.1 wurde zurückgezogen!

### ISSUE THREAD

**Issue by cRemE-fReSh** [x-jokay/docker-ccu-historian#4]
Die V2.3.1 wurde auf Grund eines Fehlers zurückgezogen.

Siehe https://github.com/mdzio/ccu-historian/issues/203 
https://github.com/mdzio/ccu-historian/releases/tag/2.3.1
https://homematic-forum.de/forum/viewtopic.php?f=38&t=54635

**Comment by x-jokay** [comment]
Vielen Dank für die Info, das Release `2.3.1` wird nun auch nicht mehr als Container angeboten.
