### ISSUE TITLE
Zugriff auf Datenbank-Web-Oberfläche ermöglichen

### ISSUE THREAD

**Issue by mdzio** [x-jokay/docker-ccu-historian#5]
Der Zugriff auf die Datenbankoberfläche (Werkzeuge → Datenbank) funktioniert nur von einem anderen Gerät aus, wenn die Option _database.webAllowOthers=true_ gesetzt ist. Vielleicht sollte sie mit in die Standardkonfiguration aufgenommen werden.

Siehe auch [Foren-Beitrag](https://homematic-forum.de/forum/viewtopic.php?f=38&t=57105&p=566361#p566361).

**Comment by x-jokay** [comment]
Ok, ist mit diesem [commit](https://github.com/x-jokay/docker-ccu-historian/commit/974213662bb88b8c20012e4922960f6ce7a26c04) per sofort als Standardkonfiguration im image `xjokay/ccu-historian:latest` drin.

**Comment by jokay** [comment]
@PaulMerk der Standard-Port für den Datenbank-Zugriff ist **8082** *(nicht 8085)* und muss nicht zwingend explizit im config gesetzt werden.

Per default wird `database.webAllowOthers=true` ins config geschrieben oder eben manuell falls gewünscht und das reicht völlig aus.

#### ccu-historian.config

```sh
...
database.webAllowOthers=true
...
```

Anschliessen einfach noch den richtigen Port mappen, damit auch der Zugriff via Docker network klappt.

#### docker-compose.yml

```yml
....
ports:
  - 2098:2098
  - 2099:2099
  - 8082:8082
...
```

#### Werkzeuge -> Datenbank

![image](https://user-images.githubusercontent.com/18613935/172985088-6a22cb41-5cc6-44fb-8a5d-8d4af5e13678.png)

Ich denke ich werde die Beispiele anpassen, damit diese Funktion auch verfügbar ist.

**Comment by PaulMerk** [comment]
Anmeldung öffnet sich jetzt über Port 8082 - ein Schritt weiter

was muss bei JDBC URL eingetragen werden ?

jdbc:h2:~/volume1/docker/historian/db/history findet die Datenbank nicht

Meine Datenbank mit Pfad volume1/docker/historian/db/history.mv.db

Danke
Paul

**Comment by jokay** [comment]
Keine Ahnung hab das Feature nie benutzt, resp. ich brauch keinen Zugang zur DB, da ja alles funktioniert :wink:

evtl. mal im Forum fragen?

**Comment by PaulMerk** [comment]
mach ich, danke
Paul

**Comment by jokay** [comment]
Ah schau mal [hier](https://github.com/jokay/docker-ccu-historian/issues/13#issuecomment-701339045).

**Comment by PaulMerk** [comment]
klappt

> Der Prefix der Url entspricht dem Wert vom config param database.dir='/database'. 

bei mir jdbc:h2:/database/history
 :-)
